Adjusted cartesian mesh generation for 2D meshes
mdolab/cgnsutilities pull request #66
Opened 2023-12-01 13:23 UTC by neysecco

## Purpose
Hello everyone,

The **explicitCart** and **simpleCart** functions could not generate cartesian meshes for 2D cases when used from the command line. The issue was that we could not set multiple symmetry planes from the command line, even though the Python part of these functions already had this functionality.
I adapted the parser to read multiple symmetry planes and mesh spacings. This modification should be backward-compatible.
This is further explained in the documentation of these functions ("$ cgns_utils explicitCart -h" and "$ cgns_utils simpleCart -h").

I also made minor changes to the **cartesian** function due to changes in scipy.optimize inteface and Python3 standards. However, I strongly recommend that we remove this function, since explicitCart and simpleCart give better control over mesh spacings.

## Type of change
Changes to the command-line interface

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [X] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
The code can be tested with:
$ cgns_utils explicitCart -3 -3 0 4 3 1 0.3,0.3,1.0 10.0 15 zmin,zmax 0 bg.cgns

The expected output is:
Grid Dimensions: [54, 51, 2]
Grid Ratios: [1.12192755 1.12387294 4.        ]

A new file named bg.cgns will be created with a cartesian mesh for 2D simulation.

## Checklist

- [ ] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [X] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation

2024-02-02 12:23 UTC, eirikurj requested changes
Hey, @neysecco, hope you are doing well! Sorry for the delay, and thanks for the PR! Did a quick pass and overall the changes look good, but see my comments. I would not be too worried about backwards compatibility, for these options, so if you have any alternate ideas please let us know. Aside from that, we should add some examples or tests, or both. This could be something simple as just showing how to use the command, and compare the cgns output file to a reference file. For reference we do something similar for [pyHyp tests](https://github.com/mdolab/pyhyp/blob/1bc185451af5f944f58e5553a8820c32775f4ebd/tests/test_all_examples.py#L31C21-L31C29).

2024-02-02 12:23 UTC, eirikurj commented on cgnsutilities/cgns_utils.py
> +        # Change dh to a list of integers, since we had
Comment mentions int, but the type casting below is float.

2024-02-02 12:23 UTC, eirikurj commented on cgnsutilities/cgns_utils.py
> +        # Change dh to a list of integers, since we had
Same here

2024-02-02 12:23 UTC, eirikurj commented on cgnsutilities/cgns_utils.py
> +        # to define it as a string in arg_parser to avoid
Most of the new code here is a duplication from `explicitCart`. Refactoring this into a function processing the cart inputs would be great.

2025-02-03 11:11 UTC, eirikurj approved these changes
This has been stale for over a year now. Fixed the couple of my own comments, but I suggest we merge this and add tests and other improvements in later PRs. @marcomangano please review if possible

2025-02-05 22:50 UTC, marcomangano reviewed
I agree we can add tests and cleanup the code at a later stage. The updated documentation and fixes are very useful.
I just have a comment below:

2025-02-05 22:50 UTC, marcomangano commented on cgnsutilities/cgnsutilities.py
> +                    bol = ~(((S[:-1] < x0bin) * (S[1:] < x0bin)) + ((S[:-1] > xfbin) * (S[1:] > xfbin)))
I don't understand this change.

2025-02-06 12:35 UTC, eirikurj commented on cgnsutilities/cgnsutilities.py
> +                    bol = ~(((S[:-1] < x0bin) * (S[1:] < x0bin)) + ((S[:-1] > xfbin) * (S[1:] > xfbin)))
This is essentially inverting a boolean array. This is a bit cryptic, and perhaps numpys `invert` would be more readable (see [docs here](https://numpy.org/doc/stable/reference/generated/numpy.invert.html)).

2025-02-06 18:50 UTC, marcomangano commented on cgnsutilities/cgnsutilities.py
> +                    bol = ~(((S[:-1] < x0bin) * (S[1:] < x0bin)) + ((S[:-1] > xfbin) * (S[1:] > xfbin)))
Oh ok yeah, it is a bit cryptic, you mean flipping the boolean values element-by-element? Could you just expand the comment in the code? Otherwise the PR is ready to go for me.

2025-02-10 15:10 UTC, eirikurj commented on cgnsutilities/cgnsutilities.py
> +                    bol = ~(((S[:-1] < x0bin) * (S[1:] < x0bin)) + ((S[:-1] > xfbin) * (S[1:] > xfbin)))
I added a comment on this, but not sure if this is useful. Please take a look. In any case, Ney suggests that this is not a useful function, and we should perhaps deprecate in favor of `explicitCart` and `simpleCart`.

2025-02-10 23:51 UTC, marcomangano approved these changes
Thanks for the updated comment, LGTM

2025-02-24 15:55 UTC, eirikurj approved these changes

2025-02-24 15:55 UTC, merged